# Generated by Django 4.0.5 on 2022-06-26 22:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('y_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.PositiveIntegerField(choices=[(0, 'Offer'), (1, 'Category')])),
                ('name', models.CharField(max_length=1024)),
                ('date', models.DateTimeField()),
                ('price', models.PositiveIntegerField(null=True)),
                ('parentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='y_api.shopunit')),
            ],
        ),
    ]
