# Generated by Django 4.0.5 on 2022-06-26 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('y_api', '0003_auto_20220626_2217'),
    ]

    operations = [
    ]
