# Generated by Django 4.0.5 on 2022-06-26 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('y_api', '0006_auto_20220626_2230'),
    ]

    operations = [
    ]
